config/routes.rb
Rails.application.routes.draw do
  root to: "posts#index"
  resources :posts
  #API LINKS
  get '/api/like/:user_id/:post_id' => 'api#like'
  get '/api/unlike/:user_id/:post_id' => 'api#unlike'
  get '/api/check/:user_id/:post_id' => 'api#check'
  
  get '/settings' => 'settings#settings'
  get '/profile/:username' => 'profile#profile'	
  match "/:controller(/:action(/:id))" , :via=>[:get,:post,:patch]
end

app/models/like.rb
class Like < ActiveRecord::Base
	belongs_to :user
	belongs_to :post	
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	validates_presence_of :title,:image,:hash_tag
	mount_uploader :image, PhotoUploader 
end

app/models/user.rb
class User < ActiveRecord::Base
	
	VALID_USERNAME_REGEX = /\A^[a-zA-Z0-9]+$\z/
    validates :username, presence: true, length: { maximum: 20 },
                                    format: { with: VALID_USERNAME_REGEX },
                                    uniqueness: { case_sensitive: false }
	validates :password, length: { minimum: 6 },  presence: true
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, uniqueness: true,  length: { maximum: 50 }, format: { with: VALID_EMAIL_REGEX }
	
	mount_uploader :avatar , PhotoUploader

	has_many :posts, through: :likes ,:foreign_key => :post_id
	has_many :likes
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
	def check
		if Like.find_by(:user_id=>session[:user_id],:post_id=>params[:post_id])
			render json: 1
		else
			render json: 0	
		end
	end

	def like
		like=Like.create(:user_id=>session[:user_id],:post_id=>params[:post_id])
		if like.save
			render text: "Liked"
		else
			render text: "Could not like"
		end
	end

	def unlike
		if Like.find_by(:user_id=>session[:user_id],:post_id=>params[:post_id]).destroy
			render text: "Unliked"
		else
			render text: "Could not unlike"
		end	
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private 

  def confirmed_login
  	unless session[:user_id]
  		flash[:notice]="Please Login"
  		redirect_to(:controller=>'auth',:action=>'login')
  		return false
  	else
  		return true
  	end	 	
  end	
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  
  before_action :confirmed_login , :except=>[:login,:signup,:attempt_login,:attempt_signup]
  

  def login
    if !session[:user_id].nil?
      redirect_to '/posts/index'
    end
  end

  def signup
    if !session[:user_id].nil?
      redirect_to '/posts/index'
    end
  end

  def attempt_signup
    par=user_params
  	user = User.create(par)
    user.views=0
    user.avatar = '/images/medium/profile.jpg'
  	user.save

  	if user.save
      flash[:notice] = "Signed Up successfully !"
      # Sends email to user when user is created.
      ApplicationMailer.verify_email(user).deliver_now
  		redirect_to(:action=>'login')
  	else
  		flash[:notice] = user.errors.full_messages
  		redirect_to(:action=>'signup')
  	end	
  end	

  def attempt_login
  	if params[:username].present? && params[:password].present?
  		@found_user = User.where(:username=>params[:username],:password=>params[:password]).first
  	end
  	if @found_user
  		session[:user_id] = @found_user.id
      flash[:notice] = "Successfully Logged In !"
  		redirect_to(:controller=>'posts',:action=>'index')
  	else
  		flash[:notice]="Invalid login credentials!"
  		redirect_to(:action=>'login')
  	end
  end 


  def logout
    session[:user_id]=nil
  	flash[:notice]="You have successfully logged out"
  	redirect_to(:action=>'login')
  end	
  
  def attempt_change
    user = User.find(session[:user_id])
    if user.update_attributes(:password => params[:password]) && params[:password]==params[:password_check]
      flash[:notice] = "Password Changed Successfully !!"
    else
      user.errors.each do |f,x|
        puts f,x
      end
      flash[:notice] = "Passwords do not match"
    end
    redirect_to '/settings'
  end 

  def update
    user = User.find(session[:user_id])
    if user.update_attributes(:full_name => params[:full_name],:email => params[:email],:country => params[:country],
      :about => params[:about],:website => params[:website])
      flash[:notice] = "Settings Updated !!"
    else
      puts user.errors.full_messages
      flash[:notice] = "Could Not Be Saved !!"
    end
    redirect_to '/settings'   
  end

  def profile_pic
    user = User.find(session[:user_id])
    if user.update(pic_params)
      flash[:notice] = "Profile Picture updated !!"
    else
      user.errors.each do |f,x|
        puts f,x
      end
      flash[:notice] = "Profile Picture could not be updated !!"
    end
    redirect_to '/settings'  
  end
  

  def user_params
  	params.require(:user).permit(:username,:password,:email)
  end

  def pic_params
    params.require(:user).permit(:avatar)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  require 'net/ftp'

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    @like=Like.find_by(:user_id=>session[:user_id])
    if !session[:user_id].nil?
      user=User.find(session[:user_id])
      posts = Post.where(:user_id=>user.id)
      @likes=0
      posts.each do |po|
        like = Like.where(:post_id=>po.id)
        if like  
          @likes += like.count
        end
      end
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    p=post_params
    @post = Post.new(p)
    @post.user_id = User.find(session[:user_id]).id
    @post.save

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title,:image,:hash_tag)
    end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
	def profile
		user = User.find(session[:user_id])
		@user1 = User.find_by(:username=>params[:username])
		if user.username != @user1.username
			@user1.views += 1
			@user1.save
		end
		@user1 = User.find_by(:username=>params[:username])
		posts = Post.where(:user_id=>User.find_by(:username=>params[:username]).id)
        @likes=0
        posts.each do |po|
          like = Like.where(:post_id=>po.id)
          if like  
            @likes += like.count
          end
        end
	end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :confirmed_login
  def settings
  	user = User.find(session[:user_id])
  	if user.avatar.nil?
  		user.update(:avatar => 'medium/profile.jpg')
  	end	
  end

end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>I am Programmer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>  
    
  <%= csrf_meta_tags %>
</head>
<body>

<script type="text/javascript">
  setTimeout(function() {
        $('.alert-danger').fadeOut('fast');
        }, 4000);
</script>

<script type="text/javascript">
  setTimeout(function() {
        $('.alert-info').fadeOut('fast');
        }, 4000);
</script>

<script type="text/javascript">
  setTimeout(function() {
        $('.alert-success').fadeOut('fast');
        }, 4000);
</script>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.4&appId=1454833521487237";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">I am Programmer</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="<%= root_path %>">Fun</a></li>
        <% if !session[:user_id].nil? %>
          <li><a href="/posts/new">Upload</a></li>
        <% end %>
        </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if !session[:user_id].nil? %>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Profile <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/profile/<%= User.find(session[:user_id]).username %>"><%= User.find(session[:user_id]).username %></a></li>
            <li><a href="/settings">Settings</a></li>
            <li><a href="/auth/logout">Logout</a></li>
          </ul>
        </li>
        <% else %>
          <li><a href="/auth/signup">Sign Up</a></li>
          <li><a href="/auth/login">Log In</a></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container mar70">
	
  <% flash.each do |name, msg| %>
    <% if msg=="You have successfully logged out" %>
      <div class="alert alert-success alert-dismissible" role="alert">
        <%= content_tag :div, msg, class: name %> 
      </div>
      <% elsif msg=="Password changed successfully" %>
        <div class="alert alert-info alert-dismissible" role="alert">
        <%= content_tag :div, msg, class: name %>
      </div>
      <% else %>
        <div class="alert alert-danger alert-dismissible warning" role="alert">
          <%= content_tag :div, msg, class: name %>
        </div>
      <% end %>
  <% end %>

  <%= yield %>
 
 
</div>
</div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
  <div class="col-lg-4"></div>
  <div class="col-lg-4 well" style="margin-top: 40px;">
    <h1 align= "center">New Post</h1>
    <hr class="colorgraph">
        <div class="field">
          <%= f.label :title ,style: "margin-top: 10px;"%><br>
          <%= f.text_field :title,class: "form-control input-group", placeholder: "Title", required:"",autofocus:"" %>
        </div>
        <div class="field">
          <%= f.label :image ,style: " margin-top: 10px;" %><br>
            <%= f.file_field :image,class: "form-control input-group", placeholder: "Post Image", required:"",autofocus:"" %>
        </div>
        <div class="field">
          <%= f.label :hash_tag,style: " margin-top: 10px;" %><br>
          <%= f.text_area :hash_tag,class: "form-control input-group", placeholder: "Hash tag", required:"",autofocus:"" , style: "margin-bottom:10px;" %>
        </div>
        <div class="actions">
          <%= f.submit class: "btn btn-primary btn-md" %>
        </div>
      <% end %>
      <%= link_to 'Back', posts_path, class: "btn btn-success btn-xs", style: "margin-top: 10px;" %>

   </div>
   <div class="col-lg-4"></div>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<script type="text/javascript">

  function change(userid,postid,index){

    var butt = document.getElementById("like_button"+index.toString());
    if (butt.value=="Like"){
      $.post("/api/check",
            {
                user_id: userid,
                post_id: postid
            },
            function(data, status){
                if(data==1){
                   butt.value = "Unlike";
                }
                else{
                    $.post("/api/like",
                        {
                            user_id: userid,
                            post_id: postid
                        },
                        function(data, status){
                            butt.value = "Unlike";
                        });   
                }
            });
    }
    else {
      butt.value = "Like";
      $.post("/api/unlike",
          {
              user_id: userid,
              post_id: postid
          },
          function(data, status){
          }); 
    }
  };
</script>
<script>
  history.pushState(null, null, location.href);
  window.onpopstate = function(event) {
      history.go(1);
  };  
</script>



    <div class="col-xs-6">
    <% @posts.reverse.each_with_index do |post,index| %>
        <div class=" panel panel-primary">
          <div class="panel-heading">
            <h3 class="panel-title"><%= link_to post.title, post %></h3>
          </div>
          <div class="panel-body">
                <div class="row">
                  <div class="col-xs-6">
                    <a href="<%= post_url(post) %>">
                      <% link = post.image.to_s.split('/').last %>
                      <% newlink = 'http://chashmeetsingh.com/iamprogrammer/post/image/'+post.id.to_s+'/'+link %>
                        <%= image_tag  newlink, size: "300x300",class: "img-responsive" %>
                    </a>
                  </div>
                  <div class="col-xs-1"></div>
                  <div class="col-xs-5">  
                    <%= post.hash_tag %><br>  
                    <a href="/profile/<%= post.user.username %>">@<%= post.user.username %></a><br>
                        <% if Like.find_by(:post_id=>post.id,:user_id=>session[:user_id]) %>
                          <% stat = "Unlike" %>
                        <% else %>
                          <% stat = "Like" %>
                        <% end %>
                  <% if !session[:user_id].nil? %>
                  <% count = Like.where(:post_id=>post.id).count %>  
                    <input class="btn btn-default btn-md" onclick="change(<%= User.find(session[:user_id]).id %>,<%= post.id %>,<%= index %>)" type="button" value="<%= stat %>" id="like_button<%= index %>" ><span class="badge badge-success"><%= count %></span></input>
                  <% end %>  
                  </div>
                </div>
          </div>
        </div> <% end %>
    </div>
<div class="row"> 
    <div class="col-xs-2"></div>
    
    <% if !session[:user_id].nil? %>
    <div class="span3 col-xs-4">
     <div class="side-bar"> 
           <div class="ls_profile ls_blue">
               <div> 
               <div class="col-xs-4">
                
               <% if User.find(session[:user_id]).avatar.present? %>
                  <% link = User.find(session[:user_id]).avatar.to_s.split('/').last %>
                  <% newlink = 'http://chashmeetsingh.com/iamprogrammer/user/avatar/'+User.find(session[:user_id]).id.to_s+'/'+link %>
                  <%= image_tag  newlink,  size: "100x100" %>
                <% else %>
                  <%= image_tag 'http://blog.skilledup.com/wp-content/authors/default.gif' , size: '100x100' %>
                <% end %>

                </div>
                <div class="col-xs-8 ls_profile_info">
                    <h3 class="size"><a class="img-responsive" style="color:white" href="/profile/<%= User.find(session[:user_id]).username %>"><%= User.find(session[:user_id]).username %></a></h3>
                    <p>Total Views : <%= User.find(session[:user_id]).views %></p>
                    
                    Total likes : <%= @likes %>
                </div>
           </div>
                <div class="clearfix"></div>
           </div>
       </div>
       <div class="fb-like" data-href="https://www.facebook.com/pages/I-am-Programmer/130346597300032" data-layout="button_count" data-action="like" data-show-faces="true" data-share="true"></div><br>
       <br>
<a href="https://twitter.com/CChashmeetsingh" class="twitter-follow-button" data-show-count="false" data-size="large">Follow @CChashmeetsingh</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script><br><br>
    </div>
    <% end %>

</div>    

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<div>
	<p>
	  <strong>Title:</strong>
	  <%= @post.title %>
	</p>
	<% link = @post.image.to_s.split('/').last %>
	<% newlink = 'http://chashmeetsingh.com/iamprogrammer/post/image/'+@post.id.to_s+'/'+link %>
	<p>
	  <strong>Image:</strong>
	  <%= image_tag  newlink, size: '300x300', class: "img-responsive"  %>
	</p>

	<p>
	  <strong>Hash Tag:</strong>
	  <%= @post.hash_tag %>
	</p>

	<%= link_to 'Back', posts_path %>
</div>

app/views/settings/settings.html.erb
<script type="text/javascript">
  var loadFile = function(event) {
    var output = document.getElementById('output');
    output.src = URL.createObjectURL(event.target.files[0]);
  };
</script>

<div>

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Profile Pic</a></li>
    <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Settings</a></li>
    <li role="presentation"><a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">Password Change</a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="home">
          <div class="row mar40" style="margin-top: 40px;">
          <div class="col-lg-3"></div>
            <div class="col-lg-4" >
              <h3>Profile Picture</h3>
                <% if User.find(session[:user_id]).avatar.present? %>
                        <% link = User.find(session[:user_id]).avatar.to_s.split('/').last %>
                        <% newlink = 'http://chashmeetsingh.com/iamprogrammer/user/avatar/'+User.find(session[:user_id]).id.to_s+'/'+link %>
                        <%= image_tag  newlink, size: '300x280' %>
                      <% else %>
                        <%= image_tag 'http://blog.skilledup.com/wp-content/authors/default.gif' , size: '200x200' %>
                      <% end %><br>
            </div>
            <div class="col-lg-5 mar18" style="margin-top: 15px;">           
              <%= form_for :user,url: '/auth/profile_pic' do |f| %>            
                <h4>Upload Image</h4>
                <%= f.file_field :avatar, onchange: "loadFile(event)", class: "mar13" %>
                <img id="output" height="200" width="230" alt="Image Preview" style="margin-bottom: 10px; margin-top: 15px;"/><br>
                <%= f.submit 'Update Picture', :class => "btn btn-primary mar15" %>
              <% end %>
            </div>  
          </div>    
    </div>
    <div role="tabpanel" class="tab-pane" id="profile">
      <div class="row">
        <div class="col-lg-4 col-xs-3"></div>
          <div class="col-lg-4 col-xs-3 mar40 well" style="margin-top: 40px;"> 
            <%= form_tag ('/auth/update') do %>
                  <%= label_tag :full_name , "Full Name" %>
                  <% if User.find(session[:user_id]).full_name.nil? %>
                    <%= text_field_tag :full_name, "",class: "form-control input-group", placeholder: "Full Name", required:"",autofocus:"" %><br>
                  <% else %>
                      <%= text_field_tag :full_name , User.find(session[:user_id]).full_name %><br>
                  <% end %>    
                  <%= label_tag :email, "Email Id" %>
                  <%= email_field_tag :email , User.find(session[:user_id]).email,class: "form-control input-group", placeholder: "Full Name", required:"",autofocus:"" %><br>
                  <%= label_tag :country , "Location" %>
                  <%= render 'form' %><br>
                  <%= label_tag :about , "About/Bio" %>
                  <% if User.find(session[:user_id]).full_name.nil? %>
                    <%= text_field_tag :about , "",class: "form-control input-group", placeholder: "About", required:"",autofocus:""%><br>
                  <% else %>
                      <%= text_field_tag :about , User.find(session[:user_id]).about,class: "form-control input-group", placeholder: "About", required:"",autofocus:"" %><br>
                  <% end %>
                  <%= label_tag :website , "Website" %>
                  <% if User.find(session[:user_id]).full_name.nil? %>
                    <%= text_field_tag :website,"",class: "form-control input-group", placeholder: "Website", required:"",autofocus:"" %><br>
                  <% else %>
                      <%= text_field_tag :website , User.find(session[:user_id]).website,class: "form-control input-group", placeholder: "Website", required:"",autofocus:"" %><br>
                  <% end %>
                  <%= submit_tag 'Update Details', :class => "btn btn-danger" %>
                <% end %>
          </div>
          <div class="col-lg-4 col-xs-6"></div>
        </div>      
    </div>
    <div role="tabpanel" class="tab-pane" id="messages">
      <div class="col-lg-4 mar40"></div>
      <div class="col-lg-4 mar80 well" style="margin-top: 40px;">
        <form action="/auth/attempt_change" accept-charset="UTF-8" method="post">
              <input name="utf8" type="hidden" value="&#x2713;" /><input type="hidden" name="authenticity_token" value="qs5IuO5OPxuoSJe5VHK9+iN50NOqjRSVje8z7/yp+zjaV7qghkwhnbYJ6eM1y3BB8BV9qHmhWP5JtOHEKJCyLw==" />
              <label class="pad-27" for="password">New Password</label>
              <input type="password" class="input-group form-control" name="password" id="password" placeholder="New Password" required="" autofocus=""/><br>
              <label class="pad-10" for="password_check">Retype Password</label>
              <input type="password" name="password_check" id="password_check" class="input-group form-control" placeholder="Re-type Password" required="" autofocus=""/><br>
              <input type="submit" name="commit" value="Change Password" class="btn btn-success" />
        </form>  
      </div>
      <div class="col-lg-4"></div>
    </div>
  </div>

</div> 